### ISSUE TITLE
请问 store => next => action => 的作用是什么？

### ISSUE THREAD

**Issue by zhy1** [mly-zju/chat-room#1]
chat-room/src/redux_middleware/index.js

您好，请问以下代码中的
```
function createSocketMiddleware(socket) {
  var eventFlag = false;
  return store => next => action => {
```

 store => next => action => 的作用是什么？

**Comment by mly-zju** [comment]
这个是redux中间件的写法，具体原理可以看redux官方文档中讲中间件的这一章节：[http://redux.js.org/docs/advanced/Middleware.html](http://redux.js.org/docs/advanced/Middleware.html)，描述的非常清楚。
